FIX : Création d'un sprint par défaut pour tous les projets existants
ATM-Consulting/dolibarr_module_scrumboard pull request #25
Opened 2018-02-23 14:37 UTC by ATM-Nicolas

La requête récupère maintenant les projets existants qui n'ont pas de sprints dans la table "projet_storie"

2018-03-06 16:14 UTC, aconits requested changes

2018-03-06 16:14 UTC, atm-ph commented on script/migration_stories.php
> +	$sql .= ' WHERE p.rowid NOT IN (SELECT fk_projet FROM '.MAIN_DB_PREFIX.'projet_storie)';
Ton script de migration n'a pas de set_time_limit(), donc par défaut au bout de 30sec le process sera kill
Dans ton traitement de TData tu n'as pas de `$db->begin()` et `$db->commit()` et si jamais ton script s'arrêt dans ta boucle ligne 48 `foreach($TStorieLabel as $k => $storie_label)`  en ayant fait par exemple 1 ou 2 insert alors qu'il en reste encore 3, quand tu vas relancer ton script tu vas omettre les 3 sprints manquants

Donc plusieurs questions à se poser quand tu construis ce genre de script
- Est ce que je traite la totalité des données en oneshot ou non
- Est ce que je veux commit mes requêtes au fur et à mesure 
- Dois je gérer du rollback pour interrompre moi même le script

2018-03-06 16:14 UTC, atm-ph commented on script/scrum.js.php
> +		$('tr.ligne_titre[story-k='+storie_order+'] a.visibility img').attr('src', '<?php print DOL_URL_ROOT.'/theme/md/img/switch_on_old.png'; ?>');
voir fonction : `img_picto()`

2018-03-07 09:19 UTC, ATM-Nicolas commented on script/migration_stories.php
> +	$sql .= ' WHERE p.rowid NOT IN (SELECT fk_projet FROM '.MAIN_DB_PREFIX.'projet_storie)';
Je commit dorénavant les requêtes au fur et à mesure

2018-03-13 07:24 UTC, merged